title: Great World
author: zestairlike
email: zestairlive@love.com
description: > # this means to ignore newlines until "baseurl:"
  Live, Laugh, Love..

# social links
twitter_username: zestairlike
github_username:  zestairlike

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
